version: "3.8"

services:
  mongodb:
    image: mongo:8
    container_name: shorturl_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1234
      MONGO_INITDB_DATABASE: short_url_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password1234@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: password1234

  # Redis Cache
  redis:
    image: redis:8-alpine
    container_name: shorturl_redis
    ports:
      - "16379:6379"

volumes:
  mongodb_data:
